-- Define custom autoplace control for lithium-brine
--data:extend({
--   {
--     type = "autoplace-control",
--     name = "lithium-brine",
--     category = "resource",  -- This is important to specify that it’s a resource control
--     order = "a-b",  -- The order in which the control appears
--     richness = true,  -- Enable richness (which helps control how abundant the resource is)
--     size = 3,  -- Define the patch size (it can vary depending on how sparse you want the resource)
--     default_enable = true,  -- Make sure it's enabled by default
--   }
-- })
--
-- -- Modify the autoplace properties of the existing lithium-brine resource from Space Age
-- local lithium_brine = data.raw["resource"]["lithium-brine"]
-- if lithium_brine then
--   lithium_brine.autoplace = {
--     control = "lithium-brine",  -- Refer to the newly defined autoplace control
--     order = "a[resources]-b[lithium]",  -- Order of appearance in the resource list
--     probability_expression = "1",  -- Set probability expression (100% chance)
--     richness_expression = "500",  -- Richness expression (adjust this value as needed)
--     sharpness = 1  -- Adjust sharpness of resource patches
--   }
-- end
-- data:extend({
--   {
--     type = "autoplace-control",
--     name = "lithium-brine",
--     localised_name = {"", "[entity=lithium-brine] ", {"entity-name.lithium-brine"}},
--     richness = true,
--     order = "e-b",  -- Adjust the order to your preference
--     category = "resource",
--     autoplace = {
--       sharpness = 1,
--       max_range = 32,
--       peaks = {
--         {
--           influence = 0.5,
--           noise_layer = "lithium-brine",  -- Adjust the noise layer if needed
--           noise_octaves_difference = -2,
--           noise_persistence = 0.3,
--           starting_area = false
--         }
--       }
--     }
--   }
-- })